// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'diagnosis_report.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

DiagnosisReport _$DiagnosisReportFromJson(Map<String, dynamic> json) {
  return DiagnosisReport(
    active: json['active'] as bool,
    column1: (json['column1'] as num)?.toDouble(),
    column10: (json['column10'] as num)?.toDouble(),
    column11: (json['column11'] as num)?.toDouble(),
    column12: (json['column12'] as num)?.toDouble(),
    column13: (json['column13'] as num)?.toDouble(),
    column14: (json['column14'] as num)?.toDouble(),
    column15: (json['column15'] as num)?.toDouble(),
    column16: (json['column16'] as num)?.toDouble(),
    column17: (json['column17'] as num)?.toDouble(),
    column18: (json['column18'] as num)?.toDouble(),
    column19: (json['column19'] as num)?.toDouble(),
    column2: (json['column2'] as num)?.toDouble(),
    column20: (json['column20'] as num)?.toDouble(),
    column21: (json['column21'] as num)?.toDouble(),
    column22: (json['column22'] as num)?.toDouble(),
    column23: (json['column23'] as num)?.toDouble(),
    column24: (json['column24'] as num)?.toDouble(),
    column25: (json['column25'] as num)?.toDouble(),
    column26: (json['column26'] as num)?.toDouble(),
    column27: (json['column27'] as num)?.toDouble(),
    column28: (json['column28'] as num)?.toDouble(),
    column29: (json['column29'] as num)?.toDouble(),
    column3: (json['column3'] as num)?.toDouble(),
    column30: (json['column30'] as num)?.toDouble(),
    column4: (json['column4'] as num)?.toDouble(),
    column5: (json['column5'] as num)?.toDouble(),
    column6: (json['column6'] as num)?.toDouble(),
    column7: (json['column7'] as num)?.toDouble(),
    column8: (json['column8'] as num)?.toDouble(),
    column9: (json['column9'] as num)?.toDouble(),
    comments: json['comments'] as String,
    createdBy: json['createdBy'] as String,
    createdOn: json['createdOn'] as String,
    days: json['days'] as int,
    departmentName: json['departmentName'] as String,
    fastinghrs: json['fastinghrs'] as String,
    firstName: json['firstName'] as String,
    id: json['id'] as String,
    lastName: json['lastName'] as String,
    modifiedBy: json['modifiedBy'] as String,
    modifiedOn: json['modifiedOn'] as String,
    months: json['months'] as int,
    patientInFasting: json['patientInFasting'] as bool,
    reportName: json['reportName'] as String,
    status: json['status'] as String,
    userName: json['userName'] as String,
    years: json['years'] as int,
  );
}

Map<String, dynamic> _$DiagnosisReportToJson(DiagnosisReport instance) =>
    <String, dynamic>{
      'active': instance.active,
      'column1': instance.column1,
      'column10': instance.column10,
      'column11': instance.column11,
      'column12': instance.column12,
      'column13': instance.column13,
      'column14': instance.column14,
      'column15': instance.column15,
      'column16': instance.column16,
      'column17': instance.column17,
      'column18': instance.column18,
      'column19': instance.column19,
      'column2': instance.column2,
      'column20': instance.column20,
      'column21': instance.column21,
      'column22': instance.column22,
      'column23': instance.column23,
      'column24': instance.column24,
      'column25': instance.column25,
      'column26': instance.column26,
      'column27': instance.column27,
      'column28': instance.column28,
      'column29': instance.column29,
      'column3': instance.column3,
      'column30': instance.column30,
      'column4': instance.column4,
      'column5': instance.column5,
      'column6': instance.column6,
      'column7': instance.column7,
      'column8': instance.column8,
      'column9': instance.column9,
      'comments': instance.comments,
      'createdBy': instance.createdBy,
      'createdOn': instance.createdOn,
      'days': instance.days,
      'departmentName': instance.departmentName,
      'fastinghrs': instance.fastinghrs,
      'firstName': instance.firstName,
      'id': instance.id,
      'lastName': instance.lastName,
      'modifiedBy': instance.modifiedBy,
      'modifiedOn': instance.modifiedOn,
      'months': instance.months,
      'patientInFasting': instance.patientInFasting,
      'reportName': instance.reportName,
      'status': instance.status,
      'userName': instance.userName,
      'years': instance.years,
    };
