import 'package:json_annotation/json_annotation.dart';

part 'membership_info.g.dart';

@JsonSerializable()
class MembershipInfo {
  bool active, hasMembership = false;
  int age, expiryDays, expiryDurationInMonths;
  String downloadProfileURL;
  String address,
      address1,
      address2,
      addressProof,
      addressProofPic,
      addressProofId,
      additionalQualificationMajor,
      additionalQualificationStatus,
      approvedDate,
      authroizedBy,
      birthDate,
      bloodGroup,
      branch,
      roleName,
      cardRenewal,
      cellNumber,
      city,
      comments,
      completedDate,
      country,
      countryCodeCell,
      countryCodeHome,
      countryCodeValueCell,
      countryCodeValueHome,
      createdBy,
      createdOn,
      departmentName,
      diabetes,
      diabetesFamilyHistory,
      district,
      documentName,
      duration,
      emailId,
      referredByValue,
      expiryDate,
      fees,
      firstName,
      gender,
      homeNumber,
      identifyProofBack,
      identifyProofFront,
      lastName,
      martialStatus,
      membershipId,
      membershipStatus,
      membershipType,
      modifiedBy,
      modifiedOn,
      nationalId,
      newMemberFees,
      occupation,
      oldDepartmentName,
      otherNames,
      paymentMode,
      qualification,
      receiptNo,
      recommendedBy,
      referredBy,
      renewalFees,
      registeredNurse,
      state,
      userFullName,
      userName,
      volunteer,
      workLocation,
      zipcode,
      registeredNurseDocument,
      recentPicture;
  List<String> specialSkills, otherInterests;

  String additionalInfo;

  MembershipInfo({
    this.active,
    this.address,
    this.address1,
    this.address2,
    this.addressProof,
    this.additionalInfo,
    this.addressProofPic,
    this.addressProofId,
    this.additionalQualificationMajor,
    this.additionalQualificationStatus,
    this.age,
    this.downloadProfileURL,
    this.approvedDate,
    this.authroizedBy,
    this.birthDate,
    this.bloodGroup,
    this.branch,
    this.cardRenewal,
    this.cellNumber,
    this.city,
    this.referredByValue,
    this.comments,
    this.completedDate,
    this.country,
    this.countryCodeCell,
    this.countryCodeHome,
    this.countryCodeValueCell,
    this.countryCodeValueHome,
    this.createdBy,
    this.createdOn,
    this.departmentName,
    this.diabetes,
    this.diabetesFamilyHistory,
    this.district,
    this.documentName,
    this.duration,
    this.emailId,
    this.expiryDate,
    this.expiryDays,
    this.expiryDurationInMonths,
    this.fees,
    this.firstName,
    this.gender,
    this.homeNumber,
    this.identifyProofBack,
    this.identifyProofFront,
    this.lastName,
    this.martialStatus,
    this.membershipId,
    this.membershipStatus,
    this.membershipType,
    this.modifiedBy,
    this.modifiedOn,
    this.nationalId,
    this.newMemberFees,
    this.occupation,
    this.oldDepartmentName,
    this.otherNames,
    this.paymentMode,
    this.qualification,
    this.receiptNo,
    this.recommendedBy,
    this.referredBy,
    this.renewalFees,
    this.registeredNurse,
    this.specialSkills,
    this.state,
    this.userFullName,
    this.userName,
    this.volunteer,
    this.zipcode,
    this.roleName,
    this.workLocation,
    this.hasMembership,
    this.otherInterests,
    this.registeredNurseDocument,
    this.recentPicture,
  });

  factory MembershipInfo.fromJson(Map<String, dynamic> data) =>
      _$MembershipInfoFromJson(data);

  Map<String, dynamic> toJson() => _$MembershipInfoToJson(this);
}
