// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'additional_history_dynamic.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

AdditionalHistoryDynamic _$AdditionalHistoryDynamicFromJson(
    Map<String, dynamic> json) {
  return AdditionalHistoryDynamic(
    active: json['active'] as bool,
    column1: json['column1'],
    column2: json['column2'],
    column3: json['column3'],
    column4: json['column4'],
    column5: json['column5'],
    column6: json['column6'],
    column7: json['column7'],
    column8: json['column8'],
    column9: json['column9'],
    column10: json['column10'],
    column11: json['column11'],
    column12: json['column12'],
    column13: json['column13'],
    column14: json['column14'],
    column15: json['column15'],
    column16: json['column16'],
    column17: json['column17'],
    column18: json['column18'],
    column19: json['column19'],
    column20: json['column20'],
    column21: json['column21'],
    column22: json['column22'],
    column23: json['column23'],
    column24: json['column24'],
    column25: json['column25'],
    column26: json['column26'],
    column27: json['column27'],
    column28: json['column28'],
    column29: json['column29'],
    column30: json['column30'],
    column31: json['column31'],
    column32: json['column32'],
    column33: json['column33'],
    column34: json['column34'],
    column35: json['column35'],
    column36: json['column36'],
    column37: json['column37'],
    column38: json['column38'],
    column39: json['column39'],
    column40: json['column40'],
    comments: json['comments'] as String,
    departmentName: json['departmentName'] as String,
    firstName: json['firstName'] as String,
    id: json['id'] as String,
    lastName: json['lastName'] as String,
    createdBy: json['createdBy'] as String,
    createdOn: json['createdOn'] as String,
    modifiedBy: json['modifiedBy'] as String,
    modifiedOn: json['modifiedOn'] as String,
    userName: json['userName'] as String,
  );
}

Map<String, dynamic> _$AdditionalHistoryDynamicToJson(
        AdditionalHistoryDynamic instance) =>
    <String, dynamic>{
      'active': instance.active,
      'column1': instance.column1,
      'column2': instance.column2,
      'column3': instance.column3,
      'column4': instance.column4,
      'column5': instance.column5,
      'column6': instance.column6,
      'column7': instance.column7,
      'column8': instance.column8,
      'column9': instance.column9,
      'column10': instance.column10,
      'column11': instance.column11,
      'column12': instance.column12,
      'column13': instance.column13,
      'column14': instance.column14,
      'column15': instance.column15,
      'column16': instance.column16,
      'column17': instance.column17,
      'column18': instance.column18,
      'column19': instance.column19,
      'column20': instance.column20,
      'column21': instance.column21,
      'column22': instance.column22,
      'column23': instance.column23,
      'column24': instance.column24,
      'column25': instance.column25,
      'column26': instance.column26,
      'column27': instance.column27,
      'column28': instance.column28,
      'column29': instance.column29,
      'column30': instance.column30,
      'column31': instance.column31,
      'column32': instance.column32,
      'column33': instance.column33,
      'column34': instance.column34,
      'column35': instance.column35,
      'column36': instance.column36,
      'column37': instance.column37,
      'column38': instance.column38,
      'column39': instance.column39,
      'column40': instance.column40,
      'comments': instance.comments,
      'createdBy': instance.createdBy,
      'createdOn': instance.createdOn,
      'departmentName': instance.departmentName,
      'firstName': instance.firstName,
      'id': instance.id,
      'lastName': instance.lastName,
      'modifiedBy': instance.modifiedBy,
      'modifiedOn': instance.modifiedOn,
      'userName': instance.userName,
    };
