name: native_screenshot
description: A simple plugin to take screenshots using native code (iOS & Android).
version: 0.0.5
email: Ivan Pompa-García <ivan.pompa@gmail.com>
homepage: https://gitlab.com/ivanjpg/native_screenshot
repository: https://gitlab.com/ivanjpg/native_screenshot.git
issue_tracker: https://gitlab.com/ivanjpg/native_screenshot/-/issues

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: jpg.ivan.native_screenshot
        pluginClass: NativeScreenshotPlugin
      ios:
        pluginClass: NativeScreenshotPlugin
